(()=>{
const data=globalThis.GLOSSARY_DATA,quiz=globalThis.GLOSSARY_QUIZ_DATA?.questions||{};if(!data?.terms)return;
const terms=data.terms.filter(t=>t.dictionary?.linkTarget??t.exam?.includes('重要度S：優先暗記')),byId=new Map(data.terms.map(t=>[t.id,t])),byName=new Map(data.terms.flatMap(t=>[t.name,...(t.aliases||[])].filter(Boolean).map(n=>[n,t])));
const matches=terms.flatMap(t=>[t.name,...(t.aliases||[])].filter(Boolean).map(text=>({text,term:t}))).sort((a,b)=>b.text.length-a.text.length);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const countLines=text=>String(text||'').split('<br>').length;
const multilineAttr=text=>countLines(text)>1?' data-multiline':'';
const style=document.createElement('style');style.textContent='.dictionary-link{display:inline;padding:0;border:0;border-bottom:1px dotted #073d86;background:transparent;color:#073d86;font:inherit;line-height:inherit}.dictionary-modal{position:fixed;inset:0;z-index:1000}.dictionary-modal[hidden]{display:none}.dictionary-backdrop{position:absolute;inset:0;background:#0007}.dictionary-sheet{position:absolute;left:50%;bottom:0;translate:-50% 0;width:min(100%,680px);max-height:82dvh;padding:18px 14px calc(16px + env(safe-area-inset-bottom));border-radius:18px 18px 0 0;background:#fff;color:#202428}.dictionary-sheet-scroll{max-height:calc(82dvh - 34px);overflow:auto}.dictionary-close{position:absolute;right:12px;top:9px;width:40px;height:40px;border:0;background:transparent;font-size:28px}.dictionary-category,.dictionary-reading{color:#5e666d;font-size:14px}.dictionary-sheet h2{margin:4px 44px 3px 0;color:#073d86;font-size:20px}.dictionary-sheet section{margin:15px 0}.dictionary-sheet h3{margin:0 0 5px;color:#073d86;font-size:16px}.dictionary-sheet ul{margin:0;padding-left:1.4em}.dictionary-sheet ul li{text-align:center}.dictionary-sheet .exam-list{padding-left:0;list-style:none}.dictionary-sheet .exam-list .exam-bullet{display:flex;align-items:flex-start;text-align:left}.dictionary-sheet .exam-list .exam-bullet>span{flex:0 0 1em}.dictionary-sheet .exam-list .exam-plain{text-align:center}#dictionaryContent section > div[data-multiline]{text-align:left}#dictionaryContent section > ul[data-multiline]{text-align:left}.dictionary-related,.dictionary-actions{display:flex;flex-wrap:wrap;gap:8px}.dictionary-related button,.dictionary-actions a{padding:8px 10px;border:1px solid #b9c9dc;border-radius:9px;background:#f5f8fc;color:#073d86;text-decoration:none;font:inherit}body.dictionary-open{overflow:hidden}';document.head.append(style);
const modal=document.createElement('div');modal.className='dictionary-modal';modal.hidden=true;modal.innerHTML='<div class="dictionary-backdrop" data-close></div><section class="dictionary-sheet" role="dialog" aria-modal="true" aria-labelledby="dictionaryTitle"><button type="button" class="dictionary-close" data-close aria-label="閉じる">×</button><div class="dictionary-sheet-scroll" id="dictionaryContent"></div></section>';document.body.append(modal);
let lastFocus=null;const refs=(values,term)=>{const seen=new Set();return(values||[]).map(v=>typeof v==='number'?byId.get(v):byName.get(String(v).split('：')[0])).filter(t=>t&&t.id!==term.id&&!seen.has(t.id)&&seen.add(t.id))};
const close=()=>{modal.hidden=true;document.body.classList.remove('dictionary-open');lastFocus?.focus()};
function open(term,trigger){lastFocus=trigger||lastFocus;const related=refs(term.relatedIds||term.relatedTerms||term.related,term),mixups=refs(term.mixupTerms||term.mixup,term);const defMulti=term.definition?multilineAttr(term.definition):'';const examMulti=term.exam?.length>1?multilineAttr(term.exam.join('<br>')):'';document.getElementById('dictionaryContent').innerHTML=`<div class="dictionary-category">${esc(term.category)}</div><h2 id="dictionaryTitle">${esc(term.name)}</h2>${term.reading?`<div class="dictionary-reading">${esc(term.reading)}</div>`:''}${term.definition?`<section><h3>定義</h3><div${defMulti}>${esc(term.definition)}</div></section>`:''}${term.exam?.length?`<section><h3>試験の要点</h3><ul class="exam-list"${examMulti}>${term.exam.map(v=>{const bullet=v.startsWith('・'),text=bullet?v.slice(1).trimStart():v;return `<li class="${bullet?'exam-bullet':'exam-plain'}">${bullet?'<span aria-hidden="true">・</span>':''}${esc(text)}</li>`}).join('')}</ul></section>`:''}${related.length?`<section><h3>関連語</h3><div class="dictionary-related">${related.map(t=>`<button type="button" data-term="${t.id}">${esc(t.name)}</button>`).join('')}</div></section>`:''}${mixups.length?`<section><h3>混同語</h3><div class="dictionary-related">${mixups.map(t=>`<button type="button" data-term="${t.id}">${esc(t.name)}</button>`).join('')}</div></section>`:''}<div class="dictionary-actions"><a href="index.html?card=${term.id}">用語カードで確認</a>${quiz[term.id]?`<a href="index.html?quiz=${term.id}">3択で確認</a>`:''}</div>`;modal.hidden=false;document.body.classList.add('dictionary-open');modal.querySelector('.dictionary-close').focus()}
modal.addEventListener('click',e=>{if(e.target.closest('[data-close]'))close();const b=e.target.closest('[data-term]');if(b)open(byId.get(Number(b.dataset.term)),lastFocus)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)close()});
const sheet=modal.querySelector('.dictionary-sheet'),scroll=modal.querySelector('.dictionary-sheet-scroll');let startX=0,startY=0,startedAtTop=false,tracking=false,locked=false;
sheet.addEventListener('touchstart',e=>{if(e.touches.length!==1||locked)return;const touch=e.touches[0];startX=touch.clientX;startY=touch.clientY;startedAtTop=scroll.scrollTop<=1;tracking=true},{passive:true});
sheet.addEventListener('touchcancel',()=>{tracking=false},{passive:true});
sheet.addEventListener('touchend',e=>{if(!tracking||locked)return;tracking=false;const touch=e.changedTouches[0];if(!touch||!startedAtTop)return;const dx=touch.clientX-startX,dy=touch.clientY-startY;if(dy<90||dy<=Math.abs(dx)*1.25)return;locked=true;close();setTimeout(()=>{locked=false},400)},{passive:true});
const skip='a,button,input,select,textarea,summary,h1,h2,h3,h4,h5,h6,nav,footer,script,style';
for(const root of document.querySelectorAll('[data-dictionary-content]'))for(const block of root.querySelectorAll('p,li,dd,.item-text,.info-block p')){if(block.closest(skip)||block.closest('.dictionary-modal'))continue;const used=new Set(),walker=document.createTreeWalker(block,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement?.closest(skip)?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const text=node.nodeValue,fragment=document.createDocumentFragment();let cursor=0,changed=false;while(cursor<text.length){let best=null;for(const match of matches){if(used.has(match.term.id))continue;const index=text.indexOf(match.text,cursor);if(index<0)continue;if(!best||index<best.index||(index===best.index&&match.text.length>best.match.text.length))best={index,match}}if(!best)break;fragment.append(text.slice(cursor,best.index));const button=document.createElement('button');button.type='button';button.className='dictionary-link';button.textContent=best.match.text;button.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(best.match.term,button)});fragment.append(button);used.add(best.match.term.id);cursor=best.index+best.match.text.length;changed=true}if(changed){fragment.append(text.slice(cursor));node.replaceWith(fragment)}}}
})();
